config/routes.rb
Rails.application.routes.draw do

  resources :kitties
  root 'pages#home'

  get "tacos", to: "pages#tester"
  get "about", to: "pages#about"


end

app/models/kitty.rb
class Kitty < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kitties_controller.rb
class KittiesController < ApplicationController
  before_action :set_kitty, only: [:show, :edit, :update, :destroy]

  # GET /kitties
  # GET /kitties.json
  def index
    @kitties = Kitty.all
  end

  # GET /kitties/1
  # GET /kitties/1.json
  def show
  end

  # GET /kitties/new
  def new
    @kitty = Kitty.new
  end

  # GET /kitties/1/edit
  def edit
  end

  # POST /kitties
  # POST /kitties.json
  def create
    @kitty = Kitty.new(kitty_params)

    respond_to do |format|
      if @kitty.save
        format.html { redirect_to @kitty, notice: 'Kitty was successfully created.' }
        format.json { render :show, status: :created, location: @kitty }
      else
        format.html { render :new }
        format.json { render json: @kitty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitties/1
  # PATCH/PUT /kitties/1.json
  def update
    respond_to do |format|
      if @kitty.update(kitty_params)
        format.html { redirect_to @kitty, notice: 'Kitty was successfully updated.' }
        format.json { render :show, status: :ok, location: @kitty }
      else
        format.html { render :edit }
        format.json { render json: @kitty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitties/1
  # DELETE /kitties/1.json
  def destroy
    @kitty.destroy
    respond_to do |format|
      format.html { redirect_to kitties_url, notice: 'Kitty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitty
      @kitty = Kitty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitty_params
      params.require(:kitty).permit(:name, :age, :cuteness)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def tester
  end

  def about
    # line needed to show kitties goes here
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kitties_helper.rb
module KittiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/kitties/_form.html.erb
<%= form_for(@kitty) do |f| %>
  <% if @kitty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitty.errors.count, "error") %> prohibited this kitty from being saved:</h2>

      <ul>
      <% @kitty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :cuteness %><br>
    <%= f.number_field :cuteness %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kitties/edit.html.erb
<h1>Editing Kitty</h1>

<%= render 'form' %>

<%= link_to 'Show', @kitty %> |
<%= link_to 'Back', kitties_path %>

app/views/kitties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kitties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Cuteness</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kitties.each do |kitty| %>
      <tr>
        <td><%= kitty.name %></td>
        <td><%= kitty.age %></td>
        <td><%= kitty.cuteness %></td>
        <td><%= link_to 'Show', kitty %></td>
        <td><%= link_to 'Edit', edit_kitty_path(kitty) %></td>
        <td><%= link_to 'Destroy', kitty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kitty', new_kitty_path %>

app/views/kitties/new.html.erb
<h1 id="add-kitty">Click me to add a new kitty</h1>

<div id="kitty-form">
<%= render 'form' %>
</div>

<%= link_to 'Back', kitties_path %>

app/views/kitties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kitty.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @kitty.age %>
</p>

<p>
  <strong>Cuteness:</strong>
  <%= @kitty.cuteness %>
</p>

<%= link_to 'Edit', edit_kitty_path(@kitty) %> |
<%= link_to 'Back', kitties_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MvcAdventures</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>I am about page</h1>

<% @kitties.each do |kitty| %>
  <p><%= kitty.name %></p>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/tester.html.erb
<h1>i am a test</h1>